# Generated by Django 3.2.5 on 2021-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
